services:
  backend:
    build:
      context: ./aspnetcore
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    env_file: 
      - ./aspnetcore/.env
    command: ["dotnet", "MyApp.dll"]
  database:
    image: postgres:18
    env_file:
      - ./aspnetcore/.env
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: 